### ISSUE TITLE
Additional parameters

### ISSUE THREAD

**Issue by chrisch80** [dstrigl/HtREST#278]
Hello,

my heliotherm heatpump has the software_version 2.03N.
I am currently running a perl script which I would like to replace by htrest.
However, I am currently quering some more parameters which seems to be not available with htrest (I get "not found" back) and thoase parameters are not listed here: https://htheatpump.readthedocs.io/en/latest/htparams.html

Those are:
MP,NR=14	Temp. M_Unterkuehlung
MP,NR=26	Carterheizung
MP,NR=33	Hochdruckschalter
MP,NR=37	EVU_Sperre
MP,NR=39	EQ Druckwaechter
MP,NR=49	Anforderung 2.Stufe
MP,NR=51	Expansionsventil
MP,NR=58	Heissgassollwert
MP,NR=59	Druckdifferenz HD_ND
MP,NR=61	Abtau Luftein_Verdampf_diff.
MP,NR=62	VL_RL_Temp.diff.
MP,NR=99	Stromz_Leistung2 (W)
SP,NR=1	TBF_BIT
SP,NR=70	HKR Soll_ZP_Korr
SP,NR=151	HKR Zeitprogramm
SP,NR=152	WW Zeitprogramm
SP,NR=154	BSZ HKP aktuelle Laufzeit
SP,NR=212	MKR1 Zeizprog
SP,NR=221	MKR1 Betriebsart
SP,NR=235	MKR2 Zeizprog
SP,NR=244	MKR2 Betriebsart

Is it somehow possible to add it in htrest?

Thank you & best regards,
Chris

**Comment by dstrigl** [comment]
Hi Chris, the provided htparams.csv in the project is just a subset (mostly used datapoints) of all available datapoints of the heatpump.
As described here https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source (under "Parametersatz & -definitionen") you can use the script "htcomplparams" to create a full list (CSV) of all supported datapoints of the heatpump.
You can store your own used-defined htparams.csv under ~/.htheatpump/htparams.csv, which will be used than by the htheatpump/HtREST module.

Regards,
Daniel.

**Comment by chrisch80** [comment]
Thank You, it is working.
