### ISSUE TITLE
Verbindung über Netzwerk

### ISSUE THREAD

**Issue by innriver** [dstrigl/HtREST#311]
Hallo Daniel,
vielen Dank für das tolle Tool. Es funktioniert bei mir mit meiner 12 Jahre alten Heliotherm HP12S16W-S-M-WEB einwandfrei und ich bringe auch alle Datenpunkte nach iobroker. Das Programm läuft auf einem Raspberry 3b+ unter Bookworm und einer virtuellen Python 3.11.2 Umgebung. Da ich das System aus Sicherheitsgründen nur lesend betreiben möchte und für die Einstellung weiterhin Homecontrol verwende und daher das Moxa Modem benötige verwende ich socat zum Erstellen einer virtuellen USB-Schnittstelle. Socat wird als Dienst gestartet. Allerdings wenn jetzt bestimmte Zeit kein Datenverkehr mehr besteht oder ein Fehler auftritt wird socat beendet und die virtuelle Schnittstelle ist weg. Leider liefert nach einem Neustart von socat, der im Dienst auch eingestellt ist, htrest keine Daten mehr. Ich muss nach dem Neustart von socat auch den htrest-Server neu starten.
Was kann ich tun damit htrest die neu gestartete Schnittstelle wieder findet bzw. erkennt wenn die Schnittstelle geschlossen ist und einen Neustart ausführt wenn USB wieder vorhanden ist. Oder besteht die Möglichkeit htrest direkt über TCP-IP zu betreiben.

Vielen Dank und liebe Grüße
Wolfgang

**Comment by dstrigl** [comment]
See: https://github.com/dstrigl/htheatpump/issues/597
