### ISSUE TITLE
Integration with home-assistant?

### ISSUE THREAD

**Issue by silviuk** [dstrigl/HtREST#330]
Hi, thank you for the great work. I just confirmed HtREST/htheatpump work very well on an old heatpump with old firmware, which is really amazing.

In the Readme there is a remark about integration of HtREST with home-assistant, but after searching a lot I didn't find exactly the right way to do this. The current Heliotherm support in home-assistant appears to expect a TCP-modbus connection, whereas HtREST is, well... REST. 

Can you please offer some pointers about this?

**Comment by dstrigl** [comment]
There is no "directly" home-assistant integration for HtREST (at the moment), just use REST integrations:
- [RESTful](https://www.home-assistant.io/integrations/rest/)
- [RESTful binary sensor](https://www.home-assistant.io/integrations/binary_sensor.rest/)
- [RESTful Command](https://www.home-assistant.io/integrations/rest_command/)
- [RESTful Sensor](https://www.home-assistant.io/integrations/sensor.rest/)
- [RESTful Switch](https://www.home-assistant.io/integrations/switch.rest/)
