### ISSUE TITLE
How to add additional heat pump parameters?

### ISSUE THREAD

**Issue by maxgrosse1** [dstrigl/HtREST#347]
Dear Daniel,
first of all, thank you for your great work! 
I have one question, I am using HtREST on my raspberry. How could I add additional heat pump parameters?
Kind regards,
Markus

**Comment by dstrigl** [comment]
You can create your own parameter definition file under `~/.htheatpump/htparams.csv` as described here:
https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source#Parametersatz-%26--definitionen

**Comment by maxgrosse1** [comment]
Thank you very much!
