### ISSUE TITLE
No COP and KwH  after update

### ISSUE THREAD

**Issue by reset12** [dstrigl/HtREST#352]
I found after update my system that nessesary fields like Stromz_Heizung_kWh;WMZ_Heizung_kWh;Stromz_Gesamt_kWh;Stromz_Leistung_W;COP are missing.
I use Python 3.10.

`0;0;0;1043.42;4820.67;1288.2;0.0;0.0 before update
0;0;0;0;0;0;0;0;0;0 after update`

is there any possibility to repair it ? I need the data to send it to waermepumpendatenbank.de every month.

**Comment by dstrigl** [comment]
What do you mean with "update my system"?
The heatpump firmware, your system where HtREST is running on, ...?

**Comment by reset12** [comment]
My Raspberry where HtREST was running because linux Version was out of Service.

**Comment by dstrigl** [comment]
The listed parameters like `Stromz_Heizung_kWh`, `WMZ_Heizung_kWh`, `Stromz_Gesamt_kW`, ... are not part of the default `htparams.csv` installed with the `htheatpump` module which is used by `HtREST`.

In your previous installation you added this parameters in your own used defined htparams CSV file under `~/.htheatpump/htparams.csv`, as described here: [https://htheatpump.readthedocs.io/en/latest/htpackage.html#htheatpump.htparams.HtParams](https://htheatpump.readthedocs.io/en/latest/htpackage.html#htheatpump.htparams.HtParams)

A complete list of all supported parameters of your heatpump can be generated with the `htcomplparams` script as descibed here: [https://htheatpump.readthedocs.io/en/latest/htscripts.html#htcomplparams](https://htheatpump.readthedocs.io/en/latest/htscripts.html#htcomplparams)

A short description about this can be also found here (but only German):
[https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source#Parametersatz-%26--definitionen](https://loxwiki.atlassian.net/wiki/spaces/LOX/pages/1583089663/Heliotherm+Open+Source#Parametersatz-%26--definitionen)

**Comment by reset12** [comment]
Thank you for that hint. I have forgot it in my documentation of installation steps.
It works no well.
